apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd
  labels:
    app: lnd
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lnd
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
        - name: lnd
          image: lnd
          command:
            - ./start-lnd.sh
          env:
            - name: CHAIN
              value: bitcoin
      ports:
        - containerPort: 9735
        - containerPort: 10009
      volumeMounts:
        - mountPath: /??
          name: lightning
    volumes:
      - name: lnd-data
        persistentVolumeClaim:
          claimName: bitcoind-pv-claim
