apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wcpos-com
  namespace: default
spec:
  secretName: wcpos-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: lightning.wcpos.com
  dnsNames:
    - lightning.wcpos.com
  acme:
    config:
      - dns01:
          provider: prod-cloudflare
        domains:
          - lightning.wcpos.com
