apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind
  labels:
    app: bitcoind
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
        - name: bitcoind
          image: ruimarinho/bitcoin-core:0.17
          resources:
            requests:
              cpu: 40m
          args:
            - -server
            - -rest
            - -txindex
            - -rpcuser=$(BITCOIN_RPC_USER)
            - -rpcpassword=$(BITCOIN_RPC_PASSWORD)
            - -rpcallowip=0.0.0.0/0
            - -rpcallowip=::/0
            - -rpcbind=0.0.0.0
          env:
            - name: BITCOIN_RPC_USER
              valueFrom:
                secretKeyRef:
                  name: bitcoin-secret
                  key: rpcuser
            - name: BITCOIN_RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitcoin-secret
                  key: rpcpass
          ports:
            - containerPort: 8332
              name: rpc
            - containerPort: 8333
              name: mainnet
            - containerPort: 18332
              name: test-rpc
            - containerPort: 18333
              name: testnet
            - containerPort: 18443
              name: regtest
            - containerPort: 18444
              name: regtest-rpc
          volumeMounts:
            - name: bitcoind-data
              mountPath: /home/bitcoin/.bitcoin
      volumes:
        - name: bitcoind-data
          persistentVolumeClaim:
            claimName: bitcoind-pv-claim
