apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  labels:
    app: bitcoind
spec:
  type: NodePort
  ports:
    - port: 8333
      name: mainnet
    - port: 8332
      name: rpc
  selector:
    app: bitcoind
